site_url: https://heia-fr.github.io/mkdocs-edu-howto/
site_name: Création de sites web pour l'enseignement
site_description: Création de sites web pour l'enseignement
copyright: "Copyright &copy; {{ cal.today.year }} Haute école d'ingénierie et d'architecture of Fribourg"

repo_url: https://github.com/heia-fr/mkdocs-edu-howto
repo_name: heia-fr/mkdocs-edu-howto
edit_uri: ""

extra:
  analytics:
    provider: google
    property: G-KS8PETYQVZ
  consent:
    title: Utilisation des cookie
    description: >-
      Nous utilisons des cookies pour reconnaître vos visites répétées et vos
      préférences, ainsi que pour mesurer l'efficacité de notre documentation
      et déterminer si les utilisateurs trouvent ce qu'ils recherchent.
      Avec votre consentement, vous nous aidez à améliorer notre documentation.
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/heia-fr/mkdocs-edu-howto
    - icon: fontawesome/brands/dev
      link: https://dev.to/supcik

theme:
  name: material
  language: "fr"
  font:
    text: "Roboto"
    code: "IBM Plex Mono"
  custom_dir: "overrides/"
  icon:
    logo: material/school
  favicon: "assets/images/favicon.ico"
  features:
    - content.code.annotate
    - navigation.sections
    - content.code.copy

extra_css:
  - "stylesheets/extra.css"

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  admonition: {}
  extra: {}
  smarty:
    smart_angled_quotes: true
    substitutions:
      left-angle-quote: "&laquo;&#xA0;"
      right-angle-quote: "&#xA0;&raquo;"
  mkdcomments: {}
  footnotes: {}
  codehilite: {}
  pymdownx.arithmatex:
    generic: true
  pymdownx.betterem:
    smart_enable: all
  pymdownx.tabbed: {}
  pymdownx.highlight: {}
  pymdownx.caret: {}
  pymdownx.critic: {}
  pymdownx.details: {}
  pymdownx.keys: {}
  pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji
    emoji_generator: !!python/name:materialx.emoji.to_svg
  pymdownx.inlinehilite: {}
  pymdownx.magiclink: {}
  pymdownx.mark: {}
  pymdownx.smartsymbols: {}
  pymdownx.superfences: {}
  pymdownx.tasklist:
    custom_checkbox: true
  pymdownx.tilde: {}
  mdx_math: {}
  attr_list: {}
  md_in_html: {}

plugins:
  - search
  - calendar
  - jconfig:
      items:
        - copyright
  - include-markdown:
      opening_tag: "{!"
      closing_tag: "!}"
  - awesome-pages
  - macros
  - pages-j2
