docs_dir: '../docs/'
site_dir: '../public/'

theme:
  name: material
  language: 'fr'
  font:
    text: 'Roboto'
    code: 'IBM Plex Mono'
  custom_dir: '../overrides/'
  icon:
    logo: material/school 
  favicon: 'assets/images/favicon.ico'
  features:
    - content.code.annotate

markdown_extensions:
  admonition: {}
  extra: {}
  smarty:
      smart_angled_quotes: true
      substitutions:
        left-angle-quote: "&laquo;&#xA0;"
        right-angle-quote: "&#xA0;&raquo;"
  mkdcomments: {}
  footnotes: {}
  codehilite: {}
  pymdownx.arithmatex:
    generic: true
  pymdownx.betterem:
    smart_enable: all
  pymdownx.tabbed: {}
  pymdownx.highlight: {}
  pymdownx.caret: {}
  pymdownx.critic: {}
  pymdownx.details: {}
  pymdownx.keys: {}
  pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji
    emoji_generator: !!python/name:materialx.emoji.to_svg
  pymdownx.inlinehilite: {}
  pymdownx.magiclink: {}
  pymdownx.mark: {}
  pymdownx.smartsymbols: {}
  pymdownx.superfences: {}
  pymdownx.tasklist:
    custom_checkbox: true
  pymdownx.tilde: {}
  mdx_math: {}
  attr_list: {}
  md_in_html: {}

extra_css:
  - 'stylesheets/extra.css'

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  search: {}
  include-markdown:
    opening_tag: '{!'
    closing_tag: '!}'
  awesome-pages: {}
  macros: {}
  mkdocs-simple-hooks:
    hooks:
      on_pre_build: "hooks:on_pre_build"
