name: publish-websites

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

env:
  SELECT_WEEK: 999
  SHOW_SOLUTION: 999

jobs:
  # Build site
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build mkdocs site
        uses: ./.github/actions/mkdocs-edu

      - name: Upload pages artifact
      - uses: actions/upload-pages-artifact

  # Deploy site to Github pages
  deploy:
    needs: build
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
